### ISSUE TITLE
No valid version available on install

### ISSUE THREAD

**Issue by haseeb1009** [mrmuhammadali/react-native-circular-carousel#6]
When I run '`npm install --save react-native-circular-carousal`' in my project directory. I am getting this error.

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for react-native-circular-carousal
```

**Comment by haseeb1009** [comment]
I have tried to install this repo in 3-4 projects and getting the same error.
Going to unstarted the repo, will restar if the issue got fixed.

**Comment by mrmuhammadali** [comment]
It was issue in documentation, write carousel instead of carousal. Sorry for the inconvenience.
